### ISSUE TITLE
Something went wrong installing the \"sharp\" module

### ISSUE THREAD

**Issue by markhker** [bubblydoo/lambda-layer-sharp#21]
Deploying and using the latest release zip causes the following error. I believe it has to be with the configuration change in the webpack.config file. The release from [https://github.com/Umkus/lambda-layer-sharp/releases](https://github.com/Umkus/lambda-layer-sharp/releases) works fine.

`{
    "errorType": "Error",
    "errorMessage": "\nSomething went wrong installing the \"sharp\" module\n\nCannot find module './sharp-linux-x64.node'\nRequire stack:\n- /opt/nodejs/node_modules/sharp/index.js\n- /var/task/task.js\n- /var/runtime/index.mjs\n\nPossible solutions:\n- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"\n- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"\n- Consult the installation documentation: https://sharp.pixelplumbing.com/install",
    "stack": [
        "Error: ",
        "Something went wrong installing the \"sharp\" module",
        "",
        "Cannot find module './sharp-linux-x64.node'",
        "Require stack:",
        "- /opt/nodejs/node_modules/sharp/index.js",
        "- /var/task/task.js",
        "- /var/runtime/index.mjs",
        "",
        "Possible solutions:",
        "- Install with verbose logging and look for errors: \"npm install --ignore-scripts=false --foreground-scripts --verbose sharp\"",
        "- Install for the current linux-x64 runtime: \"npm install --platform=linux --arch=x64 sharp\"",
        "- Consult the installation documentation: https://sharp.pixelplumbing.com/install",
        "    at Object.939 (/opt/nodejs/node_modules/sharp/index.js:7297:9)",
        "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:7688:41)",
        "    at Object.955 (/opt/nodejs/node_modules/sharp/index.js:3480:1)",
        "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:7688:41)",
        "    at Object.456 (/opt/nodejs/node_modules/sharp/index.js:3869:15)",
        "    at __webpack_require__ (/opt/nodejs/node_modules/sharp/index.js:7688:41)",
        "    at /opt/nodejs/node_modules/sharp/index.js:7711:37",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/sharp/index.js:7714:12)",
        "    at Module._compile (node:internal/modules/cjs/loader:1105:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)"
    ]
}
`

**Comment by hansottowirtz** [comment]
Thank you for opening this issue! This indeed went wrong because the simple require test didn't catch the binary `.node` file  that was moved in the sharp module folder. I fixed the issue and added a better test. I also made the build support arm64 Lambdas. See [v0.30.7](https://github.com/bubblydoo/lambda-layer-sharp/releases/tag/0.30.7).
