### ISSUE TITLE
Nodejs18.x build?

### ISSUE THREAD

**Issue by DynamicArray** [bubblydoo/lambda-layer-sharp#28]
Thank you for maintaining this!

A question: why does the build script use nodejs12 rather than v18 (or any newer version)?

**Comment by hansottowirtz** [comment]
Hi @DynamicArray! I think we're using node v16 as in the Dockerfile:

https://github.com/bubblydoo/lambda-layer-sharp/blob/9135a116ac8d535b158830a43da979c5fc23b9a9/Dockerfile#L5
